language: java

dist: trusty

# Pour ne pas être spammé à chaque build...
notifications:
  email: false

# Pour éviter de retélécharger les dépendances à chaque étape...
cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - oraclejdk8

# Utilisé pour écraser le step "test" de travis par défaut
script: 
  - jdk_switcher use oraclejdk8
  - mvn test
  - jdk_switcher use openjdk8 
  - mvn test

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: test
    - stage: deploy
      script: mvn install
