language: java

dist: trusty

# Pour ne pas être spammé à chaque build...
notifications:
  email: false

# Pour éviter de retélécharger les dépendances à chaque étape...
cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - oraclejdk8

stages:
  - name: compile
  - name: unit_test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: unit_test
      script: 
        - jdk_switcher use oraclejdk8
        - mvn test
    - stage: unit_test
      script: 
        - jdk_switcher use openjdk8 
        - mvn test
    - stage: deploy
      script: mvn install
