language: java

dist: trusty

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - oraclejdk8

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: test
      script: 
          - jdk_switcher use openjdk8
          - mvn test
      script: 
          - jdk_switcher use oraclejdk8
          - mvn test
    - stage: deploy
      script: mvn install
