language: java

jdk:
  - openjdk8
  - openjdk7

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script:
        -jdk_switcher use openjdk8
        -mvn compile
    - stage: test
      script: 
          -jdk_switcher use openjdk8
          -mvn test
      script: 
          -jdk_switcher use openjdk7
          -mvn test
    - stage: deploy
      script: mvn install
